services:
  backend:
    container_name: backend
    build:
      context: ./containers/dystellar-backend
      args:
        API_KEY: "testingkey"
        BACKEND_PATH: "/app/backend"
        CLIENT_ID: "unused"
        CLIENT_SECRET: "unused"
        REDIRECT_URI: "http://backend:3000/api/microsoft/callback"
        PRIVILEGED_AUTHORIZED_IP: "backend:3000"
    networks:
      - coretest
    volumes:
      - data:/app
  server:
    build:
      context: ./containers/hytale-server
      args:
        AUTH_ENCRYPT_PATH: "/var/lib/container_data/hytale-release/auth.enc"
        JAR_PLUGIN_PATH: "/var/lib/container_data/hytale-release/DystellarCore.jar"
        HYTALE_RELEASE_PATH: "/var/lib/container_data/hytale-release/$HYTALE_RELEASE_NAME"
        BASEDIR: "/var/lib/container_data/server"
        SERVER_NAME: "server"
        BACKEND: "backend:3000"
        RAM_ALLOC: "1G"
        API_KEY: "testingkey"
    container_name: server
    volumes:
      - data:/var/lib/container_data
      - /etc/machine-id:/etc/machine-id:ro
    ports:
      - "5520:5520/udp"
    attach: false
    depends_on:
      backend:
        condition: service_healthy
        restart: true
    networks:
      - coretest
  server1:
    build:
      context: ./containers/hytale-server
      args:
        AUTH_ENCRYPT_PATH: "/var/lib/container_data/hytale-release/auth.enc"
        JAR_PLUGIN_PATH: "/var/lib/container_data/hytale-release/DystellarCore.jar"
        HYTALE_RELEASE_PATH: "/var/lib/container_data/hytale-release/$HYTALE_RELEASE_NAME"
        BASEDIR: "/var/lib/container_data/server1"
        SERVER_NAME: "server1"
        BACKEND: "backend:3000"
        RAM_ALLOC: "1G"
        API_KEY: "testingkey"
    container_name: server1
    volumes:
      - data:/var/lib/container_data
      - /etc/machine-id:/etc/machine-id:ro
    ports:
      - "5521:5520/udp"
    attach: false
    depends_on:
      backend:
        condition: service_healthy
        restart: true
    networks:
      - coretest
volumes:
  data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: container_data
networks:
  coretest:
    name: coretest
    driver: bridge
