#!/bin/sh

mkdir -p "$BACKEND_PATH"
sleep 1
cd "$BACKEND_PATH"

if [ ! -f Cargo.toml ]; then
	git clone https://github.com/TAlgorhythmic/dystellar-backend-rs .
else
	git pull
fi

cat > .env << EOF
TEST_HOST=0.0.0.0
TEST_PORT=3000
TEST_CLIENT_ID=$CLIENT_ID
TEST_CLIENT_SECRET="$CLIENT_SECRET"
TEST_REDIRECT_URI="$REDIRECT_URI"
TEST_PRIVILEGED_AUTHORIZED_IP="$PRIVILEGED_AUTHORIZED_IP"
PROD_HOST=0.0.0.0
PROD_PORT=3000
PROD_CLIENT_ID=$CLIENT_ID
PROD_CLIENT_SECRET="$CLIENT_SECRET"
PROD_REDIRECT_URI="$REDIRECT_URI"
PROD_PRIVILEGED_AUTHORIZED_IP="$PRIVILEGED_AUTHORIZED_IP"
PRIVILEGE_TOKEN="$API_KEY"
EOF

exec cargo run --release
